import Link from 'next/link';

export const metadata = {
  title: {
    template: '%s | Sucoding',
    default: 'Next.JS | Sucoding',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        {children}
        <Link href='/login'>로그인</Link>
      </body>
    </html>
  );
}
